p8105_hw1_zq2209
================
Zining Qi
2022-09-21

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

# Problem 1

``` r
data("penguins", package = "palmerpenguins")
```

``` r
# Getting information about data
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

``` r
ncol(penguins)
```

    ## [1] 8

``` r
nrow(penguins)
```

    ## [1] 344

The dataset contains 8 variables, which are species, island,
bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g, sex, and
year. Species, island and sex are qualitative variables. Others are
quantitative variables. Species, island, bill length, bill depth,
flipper length and body mass are meaningful variables that could be
explored further, such as the relationship between mass and flip length.

The size of the dataset is 344 rows by 8 columns, 344 X 8.

The mean for flipper length is 200.9mm.

``` r
# Scatter plot of flipper length and bill length.
scatterplot_penguins = ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, col = species)) + geom_point()
scatterplot_penguins
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_zq2209_files/figure-gfm/unnamed-chunk-4-1.png)<!-- -->

``` r
ggsave("scatterplot_penguins.pdf", plot = scatterplot_penguins)
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values (geom_point).

# Problem 2

``` r
# Creating the data frame
set.seed(1)
df2 = tibble(normal_vec = rnorm(10),
             logic_vec = normal_vec > 0,
             char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
             factor_vec = factor(c("A", "B", "C", "A", "A", "B", "B", "B", "C", "C"))
)
df2
```

    ## # A tibble: 10 × 4
    ##    normal_vec logic_vec char_vec factor_vec
    ##         <dbl> <lgl>     <chr>    <fct>     
    ##  1     -0.626 FALSE     a        A         
    ##  2      0.184 TRUE      b        B         
    ##  3     -0.836 FALSE     c        C         
    ##  4      1.60  TRUE      d        A         
    ##  5      0.330 TRUE      e        A         
    ##  6     -0.820 FALSE     f        B         
    ##  7      0.487 TRUE      g        B         
    ##  8      0.738 TRUE      h        B         
    ##  9      0.576 TRUE      i        C         
    ## 10     -0.305 FALSE     j        C

``` r
summary(df2)
```

    ##    normal_vec      logic_vec         char_vec         factor_vec
    ##  Min.   :-0.8356   Mode :logical   Length:10          A:3       
    ##  1st Qu.:-0.5462   FALSE:4         Class :character   B:4       
    ##  Median : 0.2566   TRUE :6         Mode  :character   C:3       
    ##  Mean   : 0.1322                                                
    ##  3rd Qu.: 0.5537                                                
    ##  Max.   : 1.5953

``` r
# Taking mean for each vector
normal_vec = pull(df2, 1)
logic_vec = pull(df2, 2)
char_vec = pull(df2, 3)
factor_vec = pull(df2, 4)
mean(normal_vec)
```

    ## [1] 0.1322028

``` r
mean(logic_vec)
```

    ## [1] 0.6

``` r
mean(char_vec)
```

    ## Warning in mean.default(char_vec): argument is not numeric or logical: returning
    ## NA

    ## [1] NA

``` r
mean(factor_vec)
```

    ## Warning in mean.default(factor_vec): argument is not numeric or logical:
    ## returning NA

    ## [1] NA

For normal vector, the mean is 0.132. The mean for logic vector is
greater or equal to 0, which depends on the number of positive numbers.
And there are warning message when tries to get the mean for character
vector and factor vector. Because it is impossible to get mean for
text(A, B, and so on).

``` r
# Converting non-numeric variables to numeric numbers
as.numeric(logic_vec)
as.numeric(char_vec)
as.numeric(factor_vec)
```

The number of logic vector doesn’t change, but the type changes from
logic number to numeric variable. After changing the type of character
vector, the value becomes to NA. This means it is unable to assign
number to this variable. For factor number, the value change to 1,2,3.
This means there are three levels, each number assign a level number.
This actually explains why message error occurs listed above. It is
impossible to take mean for character, which even can’t assign numbers
to it, and factors, which although could assign numbers, it doesn’t make
any sense to take means for different levels.
